// AUTO-GENERATED by scripts/measure-hero-aspect.ts — do not edit by hand.
// slug -> hero image aspect ratio (width / height).
export const HERO_ASPECT: Record<string, number> = {
  "golden-luxuria": 1,
  "golden-heaven": 0.9126,
  "golden-residency": 1.5004,
  "golden-square-bharuch": 1.7095,
  "golden-nirvana": 1.5,
  "golden-villa": 1.4998,
  "golden-homes": 1.3333,
  "golden-palm-villa": 1.3451,
  "golden-square": 2.2792,
  "golden-palm-plaza": 2.2274
};
