// AUTO-GENERATED by scripts/gen-project-gallery.ts — do not edit by hand.
// slug -> every gallery-worthy image filename in public/projects/<slug>/.
export const PROJECT_GALLERY: Record<string, string[]> = {
  "golden-luxuria": [
    "Building_Front_Elevation_Courtyard_View.webp",
    "Main_Entrance_Gate_Day_Perspective.webp",
    "Building_Full_Front_Elevation_Golden_Hour.webp",
    "Interior_Entrance_Lobby_Reception.webp",
    "Landscape_Zen_Garden_Buddha_Statue.webp",
    "Landscape_Garden_Walking_Track.webp",
    "Building_Side_Elevation_Daylight.webp",
    "Children_Play_Area_Community_Park.webp",
    "Interior_Fitness_Gym_Amenities.webp",
    "Interior_Recreation_Indoor_Games_Room.webp",
    "Interior_Banquet_Hall_Formal_Setup.webp",
    "Residential_Complex_Birdview_Aerial.webp"
  ],
  "golden-heaven": [
    "Building_Full_Elevation_Twilight.webp",
    "Main_Entrance_Gate_Day_View.webp",
    "Building_Front_Perspective_Daylight.webp",
    "Garden_Landscaping_Water_Feature.webp",
    "Interiors_Gymnasium 2.webp",
    "Garden_Seating_Aesthetic_Bench.webp",
    "Children_Play_Area_Aerial.webp",
    "Residential_Complex_Birdview_Aerial.webp",
    "Interiors_Indoor_Games 2.webp",
    "Garden_Landscaping_Lawn_Area.webp",
    "Sunken_Seating_and_Parking.webp",
    "Interiors_Banquet_Hall 2.webp",
    "Children_Play_Area_Amenities.webp"
  ],
  "golden-residency": [
    "Building_Full_Front_Elevation_Day.webp",
    "Building_Central_Tower_Twilight.webp",
    "Main_Entrance_Gate_Retail_Day.webp",
    "Building_Side_Elevation_Daylight.webp",
    "Landscape_Courtyard_Garden_Twilight.webp",
    "Courtyard_Garden_Aerial_Night.webp",
    "Interior_Entrance_Lobby_Reception.webp",
    "Interior_Fitness_Gym.webp",
    "Interior_Indoor_Games_Room.webp",
    "Interior_Banquet_Hall.webp",
    "Children_Play_Area.webp",
    "Residential_Complex_Birdview_Aerial.webp"
  ],
  "golden-square-bharuch": [
    "Building_Street_Perspective_View.webp",
    "new Cam_09.webp",
    "Entrance Foyer-Final.webp",
    "Exterior_Walkway_Ivy_Lights.webp",
    "Food court-04.webp",
    "Theater lobby-06.webp",
    "Building_Front_Daylight_Full_Elevation.webp",
    "Cinemas entry-01.webp",
    "Passage.webp",
    "Interior_Atrium_Mall_View.webp",
    "Entrance_Parking_Ramp_Close_up.webp"
  ],
  "golden-nirvana": [
    "Building_Side_Front_Corner_Perspective.webp",
    "Main_Entrance_Gate.webp",
    "Landscape_Garden_Zen_Seating_Area.webp",
    "Garden_and_Tower_View.webp",
    "Bungalow_Entrance_Parking_Day.webp",
    "Landscape_Garden_Sunken_Seating.webp",
    "Bungalow_Internal_Road_Parking_View.webp",
    "Amenity_Area_Aerial.webp",
    "Landscape_Garden_Aesthetic_Seating.webp",
    "Bungalow_Main_Front_Elevation_Perspective.webp",
    "Community_Park_Aerial_Birdview.webp",
    "Community_Park_Children_Play_Area_Detail.webp",
    "Community_Park_Ground_Perspective.webp",
    "Exterior_Frontage_Aerial.webp",
    "Residential_Complex_Birdview_Night_Aerial.webp",
    "Building_Low_Angle_Street_View.webp",
    "Childrens_Play_Area.webp"
  ],
  "golden-villa": [
    "Bungalow_Main_Front_Elevation_Day.webp",
    "Main_Entrance_Gate_Day_Perspective.webp",
    "Landscape_Garden_Seating_Ground_View.webp",
    "Landscape_Zen_Garden_Buddha_Statue.webp",
    "Community_Park_Aerial_Birdview.webp",
    "Bungalow_Full_Front_View_Daylight.webp",
    "Bungalow_Main_Front_Elevation_Night.webp"
  ],
  "golden-homes": [
    "Bungalow_Full_Front_View_Night.webp",
    "Community_Park_Area_Amenities.webp",
    "Bungalow_Entrance_Parking_View.webp",
    "Bungalow_Full_Front_View_Day.webp",
    "Bungalow_Internal_Road_Perspective.webp",
    "Bungalow_Side_Elevation_Landscaping.webp"
  ],
  "golden-palm-villa": [
    "Bungalow_Street_Landscape_Night_Perspective.webp",
    "Community_Park_And_Landscaping_Aerial.webp",
    "Bungalow_Street_Level_Day_View.webp",
    "Landscape_Garden_Gazebo_and_Waterpond.webp",
    "Clubhouse_Exterior_Day.webp"
  ],
  "golden-square": [
    "Building_Main_Front_Elevation_Day.webp",
    "Interior_Courtyard_Seating_Area.webp",
    "Building_Street_Perspective_View.webp",
    "Interior_Atrium_Mall_View.webp",
    "Interior_Mall_Retail_Floor.webp",
    "Interior_Office_Block_Atrium.webp",
    "Building_Front_Elevation_Parking_View.webp"
  ],
  "golden-palm-plaza": [
    "Commercial_Plaza_Gate_Side_Night_Perspective.webp",
    "Commercial_Plaza_Main_Front_Elevation_Day.webp",
    "Commercial_Plaza_Gate_Side_Night_Perspective (1) 1.webp",
    "Commercial_Plaza_Main_Front_Elevation_Day 1.webp"
  ]
};
