// Builds a static slug -> [all gallery-worthy image filenames] map so the
// gallery can show every photo in public/projects/<slug>/ without opening the
// directory at request time (keeps fs out of the /project/[slug] serverless
// function, same rationale as scripts/measure-hero-aspect.ts).
//
// Plan/master/layout drawings are excluded — those belong to the Floor Plans
// and Master Plan sections. Curated order (hero → overview → amenities →
// gallery from projectMedia) leads, then any remaining photos, sorted.
//
//   npx tsx scripts/gen-project-gallery.ts

import { readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { PROJECTS } from "../src/lib/projects.ts";
import { getProjectMedia } from "../src/lib/projectMedia.ts";

const PROJECTS_DIR = path.join(process.cwd(), "public", "projects");
// Line-drawing / non-photo assets to keep out of the gallery.
const PLAN_RE = /(plan|layout|basement)/i;
const WEBP_RE = /\.webp$/i;

function planFilesFromData(slug: string): Set<string> {
  const p = PROJECTS.find((x) => x.slug === slug);
  const out = new Set<string>();
  const add = (src?: string) => {
    if (src) out.add(src.split("/").pop() as string);
  };
  const d = p?.detail;
  if (!d) return out;
  for (const g of d.floorPlans?.groups ?? [])
    for (const pl of g.plans ?? []) add(pl.image?.src);
  add(d.masterPlan?.image?.src);
  return out;
}

function galleryFor(slug: string): string[] {
  let files: string[];
  try {
    files = readdirSync(path.join(PROJECTS_DIR, slug));
  } catch {
    return [];
  }
  const planSet = planFilesFromData(slug);
  const allowed = new Set(
    files.filter(
      (f) => WEBP_RE.test(f) && !PLAN_RE.test(f) && !planSet.has(f),
    ),
  );

  const ordered: string[] = [];
  const push = (f?: string) => {
    if (f && allowed.has(f) && !ordered.includes(f)) ordered.push(f);
  };

  const media = getProjectMedia(slug);
  if (media) {
    push(media.hero);
    media.overview.forEach(push);
    push(media.amenities);
    media.gallery.forEach(push);
  }
  // Append any remaining photos not already placed, sorted for stability.
  [...allowed].sort().forEach(push);
  return ordered;
}

const map: Record<string, string[]> = {};
for (const p of PROJECTS) {
  const list = galleryFor(p.slug);
  if (list.length > 0) map[p.slug] = list;
}

const body =
  "// AUTO-GENERATED by scripts/gen-project-gallery.ts — do not edit by hand.\n" +
  "// slug -> every gallery-worthy image filename in public/projects/<slug>/.\n" +
  "export const PROJECT_GALLERY: Record<string, string[]> = " +
  JSON.stringify(map, null, 2) +
  ";\n";

writeFileSync(path.join(process.cwd(), "src", "lib", "projectGallery.ts"), body, "utf8");
console.log(`wrote ${Object.keys(map).length} projects -> src/lib/projectGallery.ts`);
