// Measures every project hero image once and writes a static slug -> aspect
// ratio map to src/lib/heroAspect.ts. Keeping this at build time (not in the
// /project/[slug] server route) avoids bundling sharp + the whole public/
// image folder into the Vercel function. Rendering is unaffected — the route
// just reads these numbers instead of opening files at runtime.
//
//   node scripts/measure-hero-aspect.ts

import { writeFileSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";
import { PROJECTS } from "../src/lib/projects.ts";
import { getProjectMedia } from "../src/lib/projectMedia.ts";

const base = process.env.NEXT_PUBLIC_PROJECT_IMAGE_BASE ?? "/projects";

async function aspectFor(slug: string, heroFromDetail?: string) {
  const media = getProjectMedia(slug);
  const rel = media?.hero ? `${slug}/${media.hero}` : heroFromDetail;
  if (!rel) return undefined;
  if (!base.startsWith("/")) return undefined;
  try {
    const filePath = path.join(process.cwd(), "public", base, rel);
    const { width, height } = await sharp(filePath).metadata();
    if (!width || !height) return undefined;
    return width / height;
  } catch {
    return undefined;
  }
}

async function main() {
  const map: Record<string, number> = {};
  for (const p of PROJECTS) {
    const a = await aspectFor(p.slug, p.detail?.hero?.image?.src);
    if (a) map[p.slug] = Math.round(a * 10000) / 10000;
  }

  const body =
    "// AUTO-GENERATED by scripts/measure-hero-aspect.ts — do not edit by hand.\n" +
    "// slug -> hero image aspect ratio (width / height).\n" +
    "export const HERO_ASPECT: Record<string, number> = " +
    JSON.stringify(map, null, 2) +
    ";\n";

  const out = path.join(process.cwd(), "src", "lib", "heroAspect.ts");
  writeFileSync(out, body);
  console.log(`Wrote ${Object.keys(map).length} entries to ${out}`);
}

main();
